version: 0.1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "git-task:2"
        LoadBalancerInfo:
          ContainerName: "handson"
          ContainerPort: 80